name: cs726-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - binutils_impl_linux-64=2.36.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-compiler=1.5.2
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cpuonly=2.0
  - cryptography=38.0.4
  - cxx-compiler=1.5.2
  - ffmpeg=4.3
  - flit-core=3.6.0
  - freetype=2.12.1
  - fsspec=2023.1.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.36.1
  - lerc=3.0
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libffi=3.2.1
  - libiconv=1.16
  - libidn2=2.3.2
  - libpng=1.6.37
  - libtasn1=4.16.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lightning-utilities=0.6.0.post0
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openh264=2.1.1
  - openssl=1.1.1o
  - pillow=9.3.0
  - pip=22.3.1
  - pycparser=2.21
  - pyemd=0.5.1
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.0
  - python_abi=3.8
  - pytorch=1.12.1
  - pytorch-lightning=1.9.0
  - pytorch-mutex=1.0
  - pyyaml=6.0
  - readline=7.0
  - requests=2.28.1
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.33.0
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - torchaudio=0.12.1
  - torchmetrics=0.11.1
  - torchvision=0.13.1
  - tqdm=4.64.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - urllib3=1.26.14
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.2
    - bleach==6.0.0
    - blessed==1.20.0
    - cachetools==5.3.0
    - chamferdist==1.0.0
    - click==8.1.3
    - comm==0.1.2
    - contourpy==1.0.7
    - croniter==1.3.8
    - cycler==0.11.0
    - dateutils==0.6.12
    - debugpy==1.6.6
    - decorator==5.1.1
    - deepdiff==6.2.3
    - defusedxml==0.7.1
    - dnspython==2.3.0
    - email-validator==1.3.1
    - executing==1.2.0
    - fastapi==0.88.0
    - fastjsonschema==2.16.2
    - fonttools==4.38.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - greenlet==2.0.2
    - grpcio==1.51.1
    - h11==0.14.0
    - httpcore==0.16.3
    - httptools==0.5.0
    - httpx==0.23.3
    - imageio==2.25.0
    - importlib-metadata==6.0.0
    - importlib-resources==5.10.2
    - inquirer==3.1.2
    - ipykernel==6.21.1
    - ipython==8.9.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.4
    - isoduration==20.11.0
    - itsdangerous==2.1.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonpointer==2.3
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.0.2
    - jupyter-console==6.4.4
    - jupyter-core==5.2.0
    - jupyter-events==0.6.3
    - jupyter-server==2.2.1
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.5
    - kiwisolver==1.4.4
    - lightning==1.9.0
    - lightning-cloud==0.5.22
    - markdown==3.4.1
    - markdown-it-py==2.1.0
    - markupsafe==2.1.2
    - matplotlib==3.6.3
    - matplotlib-inline==0.1.6
    - mdurl==0.1.2
    - mistune==2.0.4
    - msgpack==1.0.4
    - multidict==6.0.4
    - nbclassic==0.5.1
    - nbclient==0.7.2
    - nbconvert==7.2.9
    - nbformat==5.7.3
    - nest-asyncio==1.5.6
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - oauthlib==3.2.2
    - ordered-set==4.1.0
    - orjson==3.8.5
    - packaging==22.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.6.2
    - prometheus-client==0.16.0
    - prompt-toolkit==3.0.36
    - protobuf==3.20.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydantic==1.10.4
    - pygments==2.14.0
    - pyjwt==2.6.0
    - pynvim==0.4.3
    - pyparsing==3.0.9
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-dotenv==0.21.1
    - python-editor==1.0.4
    - python-json-logger==2.0.4
    - python-multipart==0.0.5
    - pytz==2022.7.1
    - pyzmq==25.0.0
    - qtconsole==5.4.0
    - qtpy==2.3.0
    - readchar==4.0.3
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986==1.5.0
    - rfc3986-validator==0.1.1
    - rich==13.3.1
    - rsa==4.9
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - send2trash==1.8.0
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.2
    - starlette==0.22.0
    - starsessions==1.3.0
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - terminado==0.17.1
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tornado==6.2
    - traitlets==5.9.0
    - ujson==5.7.0
    - uri-template==1.2.0
    - uvicorn==0.20.0
    - uvloop==0.17.0
    - watchfiles==0.18.1
    - wcwidth==0.2.6
    - webcolors==1.12
    - webencodings==0.5.1
    - websocket-client==1.5.1
    - websockets==10.4
    - werkzeug==2.2.2
    - widgetsnbextension==4.0.5
    - yarl==1.8.2
    - zipp==3.12.1
